### ISSUE TITLE
Couldn't destroy a service when the app is destroyed

### ISSUE THREAD

**Issue by vijayviji** [dokku/dokku-mariadb#22] opened 2015-10-01 05:16 UTC
When I tried to destroy MariaDB service, it comes back and says, "linked app can't be deleted". But the app is already destroyed and when I tried to unlink, it says "app is not available to unlink".

So, I've to create the app again just to destroy MariaDB service.

**Comment by josegonzalez** [comment] 2015-10-01 14:57
Can you paste a list of commands that we can use to reproduce the issue?

**Comment by vijayviji** [comment] 2015-10-01 16:48
dokku apps:create test_app
dokku mariadb:create test_db
dokku mariadb:link test_db test_app
dokku apps:destroy test_app
dokku mariadb:destroy test_db ---> "Cannot delete linked service"
dokku mariadb:unlink test_db test_app ---> "App test_app does not exist"
test_db can't be deleted now. There's no other way I could find to delete 'test_db' other than creating 'test_app' and delete this.

**Comment by Flink** [comment] 2015-10-03 11:07
This should be fixed with latest master. I just tested and I didn’t run into your problem. We added a hook to unlink automatically apps linked to services when the former are destroyed. So try to update to latest master on the plugin (and what version of dokku do you have?)

**Comment by josegonzalez** [comment] 2015-10-12 19:42
@vijayviji *bump*

**Comment by vijayviji** [comment] 2015-10-13 03:01
I didn't run with the latest master. If you don't face the issue,  please close this.

**Comment by josegonzalez** [comment] 2015-10-13 04:48
If you can upgrade your current mariadb plugin install to the latest master and retest this on your end, that would help us confirm the issue is actually fixed. If you don't confirm, how will we know we fixed the right thing?

**Comment by vijayviji** [comment] 2015-10-14 19:41
@josegonzalez I'll try this weekend.

**Comment by josegonzalez** [comment] 2015-10-27 02:01
@vijayviji *bump*

**Closed** 2016-05-04 06:21 UTC
Labels: needs more info
